name: Build Artifacts

permissions:
  contents: write

on:
  push:
    branches:
      - '*'

jobs:
  build-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6

    - name: NuGet Restore
      run: dotnet restore

    - name: Build and Publish project
      run: dotnet publish BattleBitAPIRunner/BattleBitAPIRunner.csproj -c Release -o ./publish --self-contained false --framework net6.0 --runtime win-x64

    - name: Build nuget
      run: dotnet build BattleBitAPIRunner/BattleBitAPIRunner.csproj -c Release

    - name: Create NuGet package
      run: dotnet pack BBRAPIModules/BBRAPIModules.csproj --configuration Release --output ./nuget

    - name: Upload NuGet package artifact
      uses: actions/upload-artifact@v2
      with:
        name: NuGet Package
        path: ./nuget/*.nupkg

    - name: Upload Release artifact
      uses: actions/upload-artifact@v2
      with:
        name: BattleBitAPIRunner-beta
        path: ./publish/*